/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */
export interface paths {
  '/api/v1/patients/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get patient by ID
     * @description Retrieves a patient by its ID
     */
    get: operations['getPatientById'];
    /**
     * Update a patient
     * @description Replaces all patient data
     */
    put: operations['updatePatient'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update patient logical state
     * @description Marks a patient as deleted or reactivates
     */
    patch: operations['updatePatientDeletionState'];
    trace?: never;
  };
  '/api/v1/patients': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get all patients
     * @description Retrieves patients by logical state
     */
    get: operations['getAllPatients'];
    put?: never;
    /**
     * Create a new patient
     * @description Creates a patient with the provided data
     */
    post: operations['createPatient'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ping': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Check healthy of the app
     * @description If the app it's alive response pong
     */
    get: operations['pong'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/patients/search': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Search and paginate patients
     * @description Filters by text, status and activity
     */
    get: operations['searchPatients'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/patients/patient-group': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a list of patients
     * @description Retrieves patients by a list of IDs
     */
    get: operations['getPatientGroup'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/patients/exists': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Validate existing patients
     * @description Returns true if the DNI exists
     */
    get: operations['existsPatientByDni'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/patients/dni/{dni}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Retrieve patient ID by DNI
     * @description Returns the patient's ID if the DNI exists in the system.
     */
    get: operations['getPatientIdByDni'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}

/**
 * Webhooks
 */
export type webhooks = Record<string, never>;

/**
 * Components
 */
export interface components {
  schemas: {
    /** @description Lista de direcciones del paciente */
    AddressUpdateDto: {
      /**
       * Format: int64
       * @description Identificador para actualizar un domicilio existente
       */
      id?: number;
      /**
       * @description Nombre de la calle
       * @example Av. Corrientes
       */
      street: string;
      /**
       * @description Departamento/Piso/Unidad (opcional)
       * @example A
       */
      apartment?: string;
      /**
       * @description Barrio (opcional)
       * @example Centro
       */
      neighborhood: string;
      /**
       * @description Ciudad
       * @example CABA
       */
      city: string;
      /**
       * @description Provincia
       * @example Buenos Aires
       */
      province: string;
      /**
       * @description Número de calle
       * @example 1234
       */
      street_number: string;
      /**
       * @description Código postal (opcional)
       * @example C1043
       */
      zip_code?: string;
      /**
       * @description Indica si es la dirección principal
       * @default true
       * @example true
       */
      is_primary: boolean;
    };
    /** @description Lista de contactos del paciente */
    ContactUpdateDto: {
      /**
       * Format: int64
       * @description Identificador para actualizar un contacto existente
       */
      id?: number;
      /**
       * @description Tipo de contacto (EMAIL, PHONE, WHATSAPP, etc.)
       * @example EMAIL
       * @enum {string}
       */
      contact_type: 'PHONE' | 'EMAIL';
      /**
       * @description Valor del contacto (email, número de teléfono, etc.)
       * @example usuario@ejemplo.com
       */
      contact_value: string;
      /**
       * @description Indica si el contacto es el principal
       * @default true
       * @example true
       */
      is_primary: boolean;
    };
    /** @description Lista de coberturas médicas del paciente */
    CoverageUpdateDto: {
      /**
       * Format: int64
       * @description Identificador para actualizar una cobertura existente
       */
      id?: number;
      /**
       * Format: int64
       * @description ID del plan de cobertura
       * @example 1
       */
      plan_id: number;
      /**
       * @description Número de afiliado
       * @example ABC123456
       */
      member_number?: string;
      /**
       * @description Indica si es la cobertura principal
       * @default true
       * @example true
       */
      is_primary: boolean;
    };
    /** @description Datos del tutor del paciente */
    GuardianUpdateDto: {
      document: string;
      /** Format: email */
      email?: string;
      phone?: string;
      bond?: string;
      verify: boolean;
      /** Format: int64 */
      user_id: number;
      first_name: string;
      last_name: string;
    };
    PatientUpdateDto: {
      /**
       * @description Número de documento del paciente
       * @example 12345678
       */
      dni: string;
      /**
       * @description Género del paciente
       * @example MALE
       * @enum {string}
       */
      gender?: 'MALE' | 'FEMALE' | 'OTHER';
      /** @description Datos del tutor del paciente */
      guardians?: components['schemas']['GuardianUpdateDto'][];
      /** @description Lista de contactos del paciente */
      contacts?: components['schemas']['ContactUpdateDto'][];
      /** @description Lista de direcciones del paciente */
      addresses?: components['schemas']['AddressUpdateDto'][];
      /** @description Lista de coberturas médicas del paciente */
      coverages?: components['schemas']['CoverageUpdateDto'][];
      /**
       * @description Nombre del paciente
       * @example Juan
       */
      first_name: string;
      /**
       * @description Apellido del paciente
       * @example Pérez
       */
      last_name: string;
      /**
       * Format: date
       * @description Fecha de nacimiento
       * @example 0034-05-26
       */
      birth_date: string;
      /**
       * @description Sexo biológico al nacer
       * @example MALE
       * @enum {string}
       */
      sex_at_birth?: 'MALE' | 'FEMALE';
      /**
       * @description Indicates if the patient is verified by a secretary
       * @example true
       */
      is_verified?: boolean;
      /**
       * @description Indica si el paciente tiene tutor
       * @example true
       */
      has_guardian?: boolean;
    };
    /** @description Lista de direcciones del paciente */
    AddressResponseDto: {
      /**
       * Format: int64
       * @description Address ID
       * @example 1
       */
      id?: number;
      /**
       * @description Street name
       * @example Av. Libertad
       */
      street?: string;
      /**
       * @description Apartment
       * @example A
       */
      apartment?: string;
      /**
       * @description Neighborhood or area
       * @example Centro
       */
      neighborhood?: string;
      /**
       * @description City
       * @example Córdoba
       */
      city?: string;
      /**
       * @description Province
       * @example Córdoba
       */
      province?: string;
      /**
       * @description Street number
       * @example 123
       */
      street_number?: string;
      /**
       * @description ZIP code
       * @example 5000
       */
      zip_code?: string;
      /**
       * @description Indicates if this is the primary address
       * @example true
       */
      is_primary?: boolean;
    };
    /** @description Lista de contactos del paciente */
    ContactResponseDto: {
      /**
       * Format: int64
       * @description Contact ID
       * @example 1
       */
      id?: number;
      /**
       * @description Contact value (email, phone, etc.)
       * @example juan.perez@email.com
       */
      contact_value?: string;
      /**
       * @description Contact type
       * @example EMAIL
       * @enum {string}
       */
      contact_type?: 'PHONE' | 'EMAIL';
      /**
       * @description Indicates if this is the primary contact
       * @example true
       */
      is_primary?: boolean;
    };
    /** @description Lista de coberturas médicas del paciente */
    CoverageResponseDto: {
      /**
       * Format: int64
       * @description Coverage ID
       * @example 1
       */
      id?: number;
      /**
       * Format: int64
       * @description Insurer ID
       * @example 1
       */
      insurer_id?: number;
      /**
       * @description Insurer acronym
       * @example OSD
       */
      insurer_acronym?: string;
      /**
       * @description Insurer name
       * @example OSDE
       */
      insurer_name?: string;
      /**
       * @description Indicates if the insurer is active
       * @example true
       */
      is_insurer_active?: boolean;
      /**
       * Format: int64
       * @description Medical coverage plan ID
       * @example 1
       */
      plan_id: number;
      /**
       * @description Medical coverage plan code
       * @example PLAN100
       */
      plan_code?: string;
      /**
       * @description Plan acronym
       * @example P100
       */
      plan_acronym?: string;
      /**
       * @description Plan name
       * @example Plan OSDE 100
       */
      plan_name?: string;
      /**
       * @description Indicates if the plan is active
       * @example true
       */
      is_plan_active?: boolean;
      /**
       * Format: int64
       * @description Insurer type ID
       * @example 2
       */
      insurer_type_id?: number;
      /**
       * @description Insurer type name
       * @example Obra social
       */
      insurer_type_name?: string;
      /**
       * @description Coverage member number
       * @example ABC123456
       */
      member_number?: string;
      /**
       * @description Indicates if this is the primary coverage
       * @example true
       */
      is_primary?: boolean;
    };
    /** @description Datos del tutor del paciente */
    GuardianDto: {
      document: string;
      /** Format: email */
      email?: string;
      phone: string;
      bond: string;
      status?: string;
      /** Format: int64 */
      user_id?: number;
      first_name: string;
      last_name: string;
      is_owner?: boolean;
    };
    PatientResponseDto: {
      /**
       * Format: int64
       * @description ID único del paciente
       * @example 1
       */
      id?: number;
      /**
       * @description Número de documento del paciente
       * @example 12345678
       */
      dni?: string;
      /**
       * @description Género del paciente
       * @example MALE
       * @enum {string}
       */
      gender?: 'MALE' | 'FEMALE' | 'OTHER';
      /**
       * @description Estado del paciente en el sistema
       * @example VERIFIED
       * @enum {string}
       */
      status?: 'MIN' | 'COMPLETE' | 'VERIFIED';
      /** @description Datos del tutor del paciente */
      guardians?: components['schemas']['GuardianDto'][];
      /** @description Lista de contactos del paciente */
      contacts?: components['schemas']['ContactResponseDto'][];
      /** @description Lista de direcciones del paciente */
      addresses?: components['schemas']['AddressResponseDto'][];
      /** @description Lista de coberturas médicas del paciente */
      coverages?: components['schemas']['CoverageResponseDto'][];
      /**
       * @description Nombre del paciente
       * @example Juan
       */
      first_name?: string;
      /**
       * @description Apellido del paciente
       * @example Pérez
       */
      last_name?: string;
      /**
       * Format: date
       * @description Fecha de nacimiento
       * @example 0034-05-26
       */
      birth_date?: string;
      /**
       * @description Sexo biológico al nacer
       * @example Masculino
       * @enum {string}
       */
      sex_at_birth?: 'MALE' | 'FEMALE';
      /**
       * @description Indica si el paciente está activo
       * @example true
       */
      is_active?: boolean;
      /**
       * @description Indica si el paciente tiene tutor
       * @example true
       */
      has_guardian: boolean;
    };
    ErrorApi: {
      /**
       * @description Timestamp when the error occurred
       * @example 2023-12-01T10:30:00
       */
      timestamp?: string;
      /**
       * Format: int32
       * @description HTTP status code
       * @example 400
       */
      status?: number;
      /**
       * @description Error code name
       * @example BAD_REQUEST
       */
      error?: string;
      /**
       * @description Error description message
       * @example Invalid request parameters
       */
      message?: string;
    };
    /** @description Lista de direcciones del paciente */
    AddressCreateDto: {
      /**
       * @description Nombre de la calle
       * @example Av. Corrientes
       */
      street: string;
      /**
       * @description Departamento/Piso/Unidad (opcional)
       * @example A
       */
      apartment?: string;
      /**
       * @description Barrio (opcional)
       * @example Centro
       */
      neighborhood: string;
      /**
       * @description Ciudad
       * @example CABA
       */
      city: string;
      /**
       * @description Provincia
       * @example Buenos Aires
       */
      province: string;
      /**
       * @description Número de calle
       * @example 1234
       */
      street_number: string;
      /**
       * @description Código postal (opcional)
       * @example C1043
       */
      zip_code?: string;
      /**
       * @description Indica si es la dirección principal
       * @default true
       * @example true
       */
      is_primary: boolean;
    };
    /** @description Lista de contactos del paciente */
    ContactCreateDto: {
      /**
       * @description Tipo de contacto (EMAIL, PHONE, WHATSAPP, etc.)
       * @example EMAIL
       * @enum {string}
       */
      contact_type: 'PHONE' | 'EMAIL';
      /**
       * @description Valor del contacto (email, número de teléfono, etc.)
       * @example usuario@ejemplo.com
       */
      contact_value: string;
      /**
       * @description Indica si el contacto es el principal
       * @default true
       * @example true
       */
      is_primary: boolean;
    };
    /** @description Lista de coberturas médicas del paciente */
    CoverageCreateDto: {
      /**
       * Format: int64
       * @description ID del plan de cobertura
       * @example 1
       */
      plan_id: number;
      /**
       * @description Número de afiliado
       * @example ABC123456
       */
      member_number?: string;
      /**
       * @description Indica si es la cobertura principal
       * @default true
       * @example true
       */
      is_primary: boolean;
    };
    PatientCreateDto: {
      /**
       * @description Número de documento del paciente
       * @example 12345678
       */
      dni: string;
      /**
       * @description Género del paciente
       * @example MALE
       * @enum {string}
       */
      gender?: 'MALE' | 'FEMALE' | 'OTHER';
      guardian?: components['schemas']['GuardianDto'];
      /** @description Lista de contactos del paciente */
      contacts?: components['schemas']['ContactCreateDto'][];
      /** @description Lista de direcciones del paciente */
      addresses?: components['schemas']['AddressCreateDto'][];
      /** @description Lista de coberturas médicas del paciente */
      coverages?: components['schemas']['CoverageCreateDto'][];
      /**
       * @description Nombre del paciente
       * @example Juan
       */
      first_name: string;
      /**
       * @description Apellido del paciente
       * @example Pérez
       */
      last_name: string;
      /**
       * Format: date
       * @description Fecha de nacimiento
       * @example 0034-05-26
       */
      birth_date: string;
      /**
       * @description Sexo biológico al nacer
       * @example MALE
       * @enum {string}
       */
      sex_at_birth?: 'MALE' | 'FEMALE';
      /**
       * @description Indicates if the patient is verified by a secretary
       * @example true
       */
      is_verified?: boolean;
      /**
       * @description Indica si el paciente tiene tutor
       * @example true
       */
      has_guardian?: boolean;
    };
    PatientDeletionRequestDto: {
      /**
       * @description Logical deletion flag
       * @example true
       */
      deleted: boolean;
    };
    PagePatientResponseDto: {
      /** Format: int64 */
      totalElements?: number;
      /** Format: int32 */
      totalPages?: number;
      /** Format: int32 */
      size?: number;
      content?: components['schemas']['PatientResponseDto'][];
      /** Format: int32 */
      number?: number;
      sort?: components['schemas']['SortObject'];
      first?: boolean;
      last?: boolean;
      /** Format: int32 */
      numberOfElements?: number;
      pageable?: components['schemas']['PageableObject'];
      empty?: boolean;
    };
    PageableObject: {
      /** Format: int64 */
      offset?: number;
      sort?: components['schemas']['SortObject'];
      paged?: boolean;
      /** Format: int32 */
      pageSize?: number;
      /** Format: int32 */
      pageNumber?: number;
      unpaged?: boolean;
    };
    SortObject: {
      empty?: boolean;
      sorted?: boolean;
      unsorted?: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

/**
 *
 */
export type $defs = Record<string, never>;

/**
 * operations
 */
export interface operations {
  getPatientById: {
    parameters: {
      query?: {
        /** @description Include inactive coverages in the response */
        includeInactiveCoverages?: boolean;
      };
      header?: never;
      path: {
        /** @description Patient ID */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Patient found */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PatientResponseDto'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorApi'];
        };
      };
    };
  };
  updatePatient: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Patient ID */
        id: number;
      };
      cookie?: never;
    };
    /** @description Complete patient payload */
    requestBody: {
      content: {
        'application/json': components['schemas']['PatientUpdateDto'];
      };
    };
    responses: {
      /** @description Patient updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PatientResponseDto'];
        };
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorApi'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorApi'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorApi'];
        };
      };
    };
  };
  updatePatientDeletionState: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Patient ID */
        id: number;
      };
      cookie?: never;
    };
    /** @description Logical deletion payload */
    requestBody: {
      content: {
        'application/json': components['schemas']['PatientDeletionRequestDto'];
      };
    };
    responses: {
      /** @description State updated */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid body */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorApi'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorApi'];
        };
      };
      /** @description Business conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorApi'];
        };
      };
    };
  };
  getAllPatients: {
    parameters: {
      query?: {
        state?: 'ACTIVE' | 'INACTIVE' | 'ALL';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Patients retrieved */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PatientResponseDto'];
        };
      };
      /** @description Invalid parameters */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorApi'];
        };
      };
    };
  };
  createPatient: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Patient payload */
    requestBody: {
      content: {
        'application/json': components['schemas']['PatientCreateDto'];
      };
    };
    responses: {
      /** @description Patient created */
      201: {
        headers: {
          /** @description URI of created resource */
          Location?: string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PatientResponseDto'];
        };
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorApi'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorApi'];
        };
      };
    };
  };
  pong: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': string;
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorApi'];
        };
      };
    };
  };
  searchPatients: {
    parameters: {
      query?: {
        q?: string;
        state?: string;
        status?: 'MIN' | 'COMPLETE' | 'VERIFIED';
        /** @description Zero-based page index (0..N) */
        page?: number;
        /** @description The size of the page to be returned */
        size?: number;
        /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
        sort?: string[];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Page retrieved */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PagePatientResponseDto'];
        };
      };
    };
  };
  getPatientGroup: {
    parameters: {
      query: {
        ids: number[];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Patients retrieved */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PatientResponseDto'];
        };
      };
      /** @description Invalid identifiers */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorApi'];
        };
      };
    };
  };
  existsPatientByDni: {
    parameters: {
      query: {
        dni: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Validation OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': boolean;
        };
      };
      /** @description Invalid DNI */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorApi'];
        };
      };
    };
  };
  getPatientIdByDni: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Patient Document */
        dni: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Patient found — ID successfully retrieved */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': number;
        };
      };
      /** @description Invalid DNI or patient not found */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorApi'];
        };
      };
    };
  };
}
